#!/bin/bash
#SBATCH --job-name=mosim_simulation
#SBATCH --time=1:00:00
#SBATCH --mem=10G
#SBATCH --cpus-per-task=1
#SBATCH --output=/data/users/vmuller/0_master_thesis/log/mosim_simulation_%J.out
#SBATCH --error=/data/users/vmuller/0_master_thesis/log/mosim_simulation_%J.err
#SBATCH --partition=pibu_el8

set -euo pipefail
echo $(date)
source "$SLURM_SUBMIT_DIR/00_config.sh"

activate_conda

DONOR_ID="HC14"
INPUTDIR="/data/users/vmuller/0_master_thesis/data/data_interleukines"
OUTPUTDIR="/data/users/vmuller/0_master_thesis/data/data_interleukines/simulated_data"

mkdir -p "$OUTPUTDIR"

Rscript "$WORKDIR/src/Synthetic_data_mosim/mosim.R" \
    --donor_name "$DONOR_ID" \
    --inputdir "$INPUTDIR" \
    --outdir "$OUTPUTDIR"